# Generated by Django 3.1.6 on 2021-02-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='메뉴ID')),
                ('menu_name_ko', models.CharField(max_length=100, verbose_name='메뉴명(한글)')),
                ('menu_name_en', models.CharField(max_length=200, verbose_name='메뉴명(영문)')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('prent_menu_id', models.FloatField(verbose_name='상위메뉴ID')),
                ('icons', models.CharField(blank=True, max_length=1000, null=True, verbose_name='아이콘')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='정렬순서')),
                ('use_yn', models.CharField(default='Y', max_length=1, verbose_name='사용여부(Y/N)')),
                ('search_yn', models.CharField(default='Y', max_length=1, verbose_name='조회여부(Y/N)')),
                ('insert_yn', models.CharField(default='Y', max_length=1, verbose_name='신규여부(Y/N)')),
                ('update_yn', models.CharField(default='Y', max_length=1, verbose_name='수정여부(Y/N)')),
                ('delete_yn', models.CharField(default='Y', max_length=1, verbose_name='삭제여부(Y/N)')),
                ('print_yn', models.CharField(default='N', max_length=1, verbose_name='출력여부(Y/N)')),
                ('batch_yn', models.CharField(default='N', max_length=1, verbose_name='생성여부(Y/N)')),
                ('excel_down_yn', models.CharField(default='Y', max_length=1, verbose_name='엑셀다운로드여부(Y/N)')),
                ('excel_up_yn', models.CharField(default='N', max_length=1, verbose_name='엑셀업로드여부(Y/N)')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('create_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='생성자ID')),
                ('update_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일시')),
                ('update_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='수정자ID')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'db_table': 'sys_menu',
                'ordering': ['-use_yn', 'sort_order'],
                'managed': False,
            },
        ),
    ]
