# Generated by Django 3.1.6 on 2021-02-23 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('menu_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='메뉴UID')),
                ('menu_cd', models.CharField(max_length=20, verbose_name='메뉴코드')),
                ('menu_name_ko', models.CharField(max_length=100, verbose_name='메뉴명(한글)')),
                ('menu_name_en', models.CharField(max_length=200, verbose_name='메뉴명(영문)')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('parent_menu_cd', models.CharField(max_length=20, verbose_name='상위메뉴코드')),
                ('icons', models.CharField(blank=True, max_length=1000, null=True, verbose_name='아이콘')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='정렬순서')),
                ('use_yn', models.CharField(default='Y', max_length=1, verbose_name='사용(Y/N)')),
                ('search_yn', models.CharField(default='Y', max_length=1, verbose_name='조회(Y/N)')),
                ('add_row_yn', models.CharField(default='Y', max_length=1, verbose_name='행추가(Y/N)')),
                ('delete_row_yn', models.CharField(default='Y', max_length=1, verbose_name='행삭제(Y/N)')),
                ('save_yn', models.CharField(default='Y', max_length=1, verbose_name='저장(Y/N)')),
                ('copy_yn', models.CharField(default='N', max_length=1, verbose_name='자료복사(Y/N)')),
                ('batch_yn', models.CharField(default='N', max_length=1, verbose_name='자료생성(Y/N)')),
                ('print_yn', models.CharField(default='N', max_length=1, verbose_name='출력(Y/N)')),
                ('excel_down_yn', models.CharField(default='Y', max_length=1, verbose_name='엑셀다운로드(Y/N)')),
                ('excel_up_yn', models.CharField(default='N', max_length=1, verbose_name='엑셀업로드(Y/N)')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('create_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='생성자ID')),
                ('update_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일시')),
                ('update_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='수정자ID')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'db_table': 'sys_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysMenuV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_uid', models.CharField(max_length=32)),
                ('menu_cd', models.CharField(max_length=20)),
                ('path_ko', models.CharField(max_length=1000)),
                ('path_en', models.CharField(max_length=1000)),
                ('menu_name_ko_dis', models.CharField(max_length=100)),
                ('menu_name_en_dis', models.CharField(max_length=200)),
                ('menu_name_ko', models.CharField(max_length=100)),
                ('menu_name_en', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('parent_menu_cd', models.CharField(max_length=32)),
                ('icons', models.CharField(max_length=1000)),
                ('sort_order', models.IntegerField()),
                ('use_yn', models.CharField(max_length=1)),
                ('search_yn', models.CharField(max_length=1)),
                ('add_row_yn', models.CharField(max_length=1)),
                ('delete_row_yn', models.CharField(max_length=1)),
                ('save_yn', models.CharField(max_length=1)),
                ('copy_yn', models.CharField(max_length=1)),
                ('batch_yn', models.CharField(max_length=1)),
                ('print_yn', models.CharField(max_length=1)),
                ('excel_down_yn', models.CharField(max_length=1)),
                ('excel_up_yn', models.CharField(max_length=1)),
                ('remark', models.CharField(max_length=2000)),
                ('create_date_time', models.DateTimeField()),
                ('create_by', models.IntegerField()),
                ('update_date_time', models.DateTimeField()),
                ('update_by', models.IntegerField()),
            ],
            options={
                'db_table': 'sys_menu_v',
                'ordering': ['-use_yn', 'sort_order'],
                'managed': False,
            },
        ),
    ]
