# Generated by Django 3.1.6 on 2021-02-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='사용자ID')),
                ('user_account', models.CharField(max_length=30, verbose_name='사용자계정')),
                ('user_name', models.CharField(max_length=50, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('person_id', models.IntegerField(verbose_name='개인ID')),
                ('hp_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='휴대전화')),
                ('email_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일')),
                ('remark', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('create_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='생성자ID')),
                ('update_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일시')),
                ('update_by', models.IntegerField(blank=True, default=-1, null=True, verbose_name='수정자ID')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'sys_user',
                'ordering': ['user_name', 'user_account'],
                'managed': False,
            },
        ),
    ]
